drop table IF EXISTS BALANCE;
create table BALANCE(BID INTEGER NOT NULL AUTO_INCREMENT, SUM DECFLOAT);
insert into BALANCE(BID, SUM) values (1,1000);
drop table IF EXISTS OPERATION_HISTORY;
create table OPERATION_HISTORY(OHID INTEGER NOT NULL AUTO_INCREMENT, UPDATE_DATE timestamp, OPERATION_TYPE VARCHAR(100) ,OPERATION_AMOUNT DECFLOAT, BALANCE DECFLOAT );
